### ISSUE TITLE
to_pdf() Error: could not convert C:/Users/xxxx/AppData/Local/R/win-library/4.2/doconv/doc-examples/example.docx

### ISSUE THREAD

**Issue by gfspiteri** [cran/doconv#1]
I am trying to used the to_pdf() function to convert a word document to pdf. I kept getting an error with my docx file so tested with the examples from the documentation:

`docx_file <- system.file(package = "doconv", "doc-examples/example.docx")`
`to_pdf(docx_file, output = "docx_example.pdf")`
`Error: could not convert C:/Users/gspiteri/AppData/Local/R/win-library/4.2/doconv/doc-examples/example.docx`

doconv::msoffice_available() returns TRUE

I am using this version of Word: Microsoft® Word for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit 

Appreciate any help. Thanks and Merry Christmas!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by gfspiteri** [comment]
Oops sorry about that!
