### ISSUE TITLE
Risky setting of default output file

### ISSUE THREAD

**Issue by pecanka** [cran/doconv#3]
Great package! Thanks for the work. To improve it, may I suggest changing the way the default output file is set to avoid overwriting the input file under certain circumstances. Currently, `output` is set via 
```
output = gsub("\\.(docx|doc|rtf)$", ".pdf", input)
``` 

which runs the risk of simply returning the name of the input file whenever the input docx filename is not in lowercase (which is not unusual on Windows). It might be safer to do something like this:

```
output = gsub("\\.(docx|doc|rtf)\\.pdf$", ".pdf", paste0(input, ".pdf"))
```

Alternatively, `ignore.case=TRUE` could be added in the `gsub` call, but that would still fail to safeguard if the input file does not have the correct extension (rare but possible).

Additionally, just to be sure, it might be a good idea to also disallow the output be identical to input altogether by adding a check for the equality of `input` and `output` right above the call to `init_working_directory()`.

Thanks again!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by pecanka** [comment]
Hi Gabor, thanks for the reminder and my apologies. I'm closing this here then.
